name: .NET CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build, Test, and Sonar Analysis
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./Source/Back-end

    steps:
      # Step 1: Set up JDK 17 (required for SonarCloud)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      # Step 2: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 3: Cache dependencies
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: ${{ runner.os }}-nuget-

      # Step 4: Install dependencies
      - name: Install dependencies
        run: dotnet restore osu.sln

      # Step 5: Run tests and collect coverage
      - name: Run tests and collect coverage
        run: |
          dotnet test osu.sln --configuration Debug --no-build `
            --collect:"XPlat Code Coverage" `
            --results-directory ./TestResults `
            --logger "trx;LogFileName=test_results.trx"
            
      # Step 6: Debug - Check generated coverage report
      - name: Debug - List TestResults directory
        run: |
          echo "Checking TestResults directory..."
          dir ./TestResults

      # Step 7: Install ReportGenerator
      - name: Install ReportGenerator
        run: dotnet tool install --global dotnet-reportgenerator-globaltool

      # Step 8: Ensure .NET tools are in PATH
      - name: Add .NET tools to PATH
        shell: powershell
        run: |
          $Env:PATH += ";$Env:USERPROFILE\.dotnet\tools"

      # Step 9: Generate Cobertura format coverage report
      - name: Generate Cobertura format
        run: |
          mkdir -p ./TestResults/Cobertura
          reportgenerator -reports:./TestResults/**/coverage.cobertura.xml \
                          -targetdir:./TestResults/Cobertura \
                          -reporttypes:Cobertura

      # Step 10: Debug - Verify Cobertura report
      - name: Debug - Verify Cobertura report
        run: |
          echo "Checking TestResults directory..."
          dir ./TestResults
          echo "Checking Cobertura directory..."
          dir ./TestResults/Cobertura

      # Step 11: Rename Cobertura report
      - name: Rename Cobertura.xml to coverage.sonarqube.xml
        run: |
          if (Test-Path "./TestResults/Cobertura/Cobertura.xml") {
            Write-Host "Cobertura.xml exists. Proceeding to rename."
            Rename-Item "./TestResults/Cobertura/Cobertura.xml" "./TestResults/Cobertura/coverage.sonarqube.xml"
          } else {
            Write-Host "Cobertura.xml not found. Exiting."
            exit 1
          }

      # Step 12: Run SonarScanner Begin
      - name: Run SonarScanner Begin
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet tool install --global dotnet-sonarscanner
          dotnet sonarscanner begin /k:"TestProjectKeySchool" /o:"ipipboy029" \
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.cs.vscoveragexml.reportsPaths="./TestResults/Cobertura/coverage.sonarqube.xml"

      # Step 13: Build solution
      - name: Build solution
        run: dotnet build osu.sln --configuration Debug --no-restore

      # Step 14: Run SonarScanner End
      - name: Run SonarScanner End
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
