name: .NET CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build, Test, and Sonar Analysis
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./Source/Back-end

    steps:

    # Step 1: Set up JDK 17 (required for SonarCloud)
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'zulu'

    # Step 2: Checkout code
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Step 3: Cache dependencies
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: ${{ runner.os }}-nuget-

    # Step 4: Install dependencies
    - name: Install dependencies
      run: dotnet restore osu.sln
      
    - name: Build the project
      run: dotnet build --configuration Release

    # Step 5: Verify the build output directory exists
    - name: Verify build output directory
      run: |
        if (Test-Path "Source/Back-end/bin/Release/net6.0") { Write-Host "Build output found." } else { Write-Host "Build output NOT found." }

    # Step 6: Install coverlet to generate coverage report in Cobertura format
    - name: Install coverlet
      run: dotnet tool install --global coverlet.console

    # Step 7: Run tests with coverage and generate Cobertura report
    - name: Run tests with coverage and generate Cobertura report
      run: |
        dotnet test --configuration Release --collect:"XPlat Code Coverage"
        coverlet ./Source/Back-end/bin/Release/net6.0/YourProject.dll --target "dotnet" --targetargs "test" --format cobertura --output ./TestResults/coverage.cobertura.xml

    # Step 8: Install SonarCloud Scanner
    - name: Install SonarCloud Scanner
      run: dotnet tool install --global dotnet-sonarscanner

    # Step 9: Prepare SonarCloud analysis
    - name: Prepare SonarCloud analysis
      run: dotnet-sonarscanner begin /k:"TestProjectKeySchool" /o:"ipipboy029" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.coverageReportPaths="TestResults/coverage.cobertura.xml"

    # Step 10: Run the build again (required for SonarCloud)
    - name: Run the build again (required for SonarCloud)
      run: dotnet build --configuration Release

    # Step 11: End SonarCloud analysis
    - name: End SonarCloud analysis
      run: dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

  deploy:
    name: Deploy with Watchtower
    runs-on: ubuntu-latest
    steps:
      - name: Pull and deploy using Watchtower
        run: |
          docker run -d --name watchtower \
          -v /var/run/docker.sock:/var/run/docker.sock \
          containrrr/watchtower --interval 300 --cleanup
