name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: ./Source/Front-end/osuapi

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    # Set up Node.js environment
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'

    # Install dependencies
    - run: npm ci

    # Build the project (if needed)
    - run: npm run build --if-present
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
          java-version: '17'
    # Run SonarCloud analysis
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1
      with:
        organization: ipipboy029  # Replace with your SonarCloud organization
        projectKey: TestProjectKeySchool    # Replace with your SonarCloud project key
        projectName: osuapi           # Replace with your project name
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Set the SONAR_TOKEN secret in GitHub repository settings

    # Optionally, you can run tests after the SonarCloud scan if desired
    # - run: npm test
