name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest
    defaults:
      run: 
        working-directory: ./Source/Front-end/osuapi

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    # Set up Node.js environment
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'

    # Install dependencies
    - run: npm ci

    # Build the project (if needed)
    - run: npm run build --if-present
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
          java-version: '17'
          distribution: 'temurin'
          
    - name: Set JAVA_HOME for SonarCloud
      run: echo "JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))" >> $GITHUB_ENV
    # Run SonarCloud analysis
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1
      with:
        entryPoint: "sonar-scanner"  # This will trigger the SonarScanner with the default arguments
        args: "-Dsonar.projectKey=TestProjectKeySchool -Dsonar.organization=ipipboy029 -Dsonar.projectName=osuapi -Dsonar.projectBaseDir=."  # Pass the project details as arguments         # Replace with your project name
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        JAVA_HOME: ${{ env.JAVA_HOME }}# Set the SONAR_TOKEN secret in GitHub repository settings

    # Optionally, you can run tests after the SonarCloud scan if desired
    # - run: npm test
